-- LEFT JOIN을 사용해서 조인 조건으로 ANIMAL_ID가 NULL 인 것이 유실된 데이터 
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o
LEFT JOIN ANIMAL_INS i ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.ANIMAL_ID is NULL
ORDER BY o.ANIMAL_ID;